### ISSUE TITLE
Download fails; no error message aside from question about password

### ISSUE THREAD

**Issue by sysfu** [Battleman/zoomdl#4] opened 2020-04-16 00:02 UTC
I'm trying to download the following URL `https://us04web.zoom.us/rec/play/6JF8Juz6rm03TtWT5QSDBPQqW9S5JqKshilKr6ELzB2xB3JSO1GjYucTNOMhfOm5-BcCHyT6-3zt5sd8?continueMode=true`

...and it keeps failing with no error aside from "Are you sure there is no password, or have you entered it correctly?"

I have tried removing the '?continueMode=true' string from the end of the URL and it makes no difference.

Environment:
Ubuntu 19.10
Python 2.7.17

Output log of command run with python -v switch attached.
[zoom.log](https://github.com/Battleman/zoomdl/files/4484234/zoom.log)

**Comment by Battleman** [comment] 2020-04-16 07:14
Thank you for the issue. 
The main problem was caused by Python2.7. The script was intended for Python3. As Python2 has reached EOL in January, I strongly encourage you to upgrade.
Nonetheless, I added support for python2.7, as well as more generic domains (in your case, `us04web`). 
I'm closing the issue. Reopen if it still doesn't work.

**Closed by Battleman** 2020-04-16 07:14 UTC

**Comment by sysfu** [comment] 2020-04-16 18:20
If anyone else comes across this issue, it turns out that you can set Python3 as the default in Ubuntu 19.10 fairly easily [using this guide.](https://exitcode0.net/ubuntu-19-10-how-to-upgrade-python-2-7-to-python-3-7/)
