### ISSUE TITLE
A "talker-face" video is downloaded while a PPT slide video is not

### ISSUE THREAD

**Issue by HengyueLi** [Battleman/zoomdl#56] opened 2021-06-10 01:53 UTC
**Describe the bug**
The program is working well. A target PPT slide video is not downloaded but a talker-face video is downloaded.

**To Reproduce**

1. just run `zoomdl.exe -u ...` it works but the wrong video is downloaded.

**Versions (please complete the following information):**
 - OS: windows zoomdl.exe

**URL**

[https://osa.zoom.us/rec/play/w9svjptOFcUJbHiP0Iy1P_2b7saPvvAKx6F45kLKx3i9Cd6w41fBwOZpoqeQiumUsParsVAXBrD-VQua.mmrka-WpxCk-hGXF?continueMode=true&_x_zm_rtaid=ANFpU88IQNqbHgqDMoMfGA.1623224976351.8bb3d381bbd47d99f81fec81bcf4bcea&_x_zm_rhtaid=248](https://osa.zoom.us/rec/play/w9svjptOFcUJbHiP0Iy1P_2b7saPvvAKx6F45kLKx3i9Cd6w41fBwOZpoqeQiumUsParsVAXBrD-VQua.mmrka-WpxCk-hGXF?continueMode=true&_x_zm_rtaid=ANFpU88IQNqbHgqDMoMfGA.1623224976351.8bb3d381bbd47d99f81fec81bcf4bcea&_x_zm_rhtaid=248)

**Comment by Battleman** [comment] 2021-06-14 10:40
I confirm I can reproduce, thanks for raising it. It seems an easy fix, the secondary video's URL follows similar guidelines to the speaker's. I'll issue a "quick" fix soon, that works for that case (without breaking the rest). Knowing Zoom, they'll probably have edge cases that don't work everything, but let's start with that.

**Comment by Battleman** [comment] 2021-06-14 15:23
Should be fixed in ea3fc5a. Check the Beta branch. Linux exec is already compiled. For windows, you can simply clone the repo and execute `wincompile.bat` in a terminal. Or wait until I get a chance to compile it myself.

**Comment by Battleman** [comment] 2021-06-14 15:32
To be clear about the changes (and for a kind of documentation):
Now zoomdl looks for metadata, and in particular an injected name `viewMp4Url`. Apparently, the projected screen is called `shareMp4Url`. Because it's not clear if the number of screens can be even higher, now it takes all those URLs, and puts them in a set, then download them one after the other. The naming convention is followed as before. If there is more than 1 URL in the page, a suffix `-screenX` (with `X` being 0 or 1) is appended to the name. If later on it is realized a higher number of screens can happen at the same time, changes will be easier (simply adding the new name of the potential third screen into the list of URLs).

**Comment by HengyueLi** [comment] 2021-06-15 02:00
I tried the new edition and it works fine. 
Well done!

**Closed** 2021-06-21 19:13 UTC
Labels: bug
