### ISSUE TITLE
Slow download

### ISSUE THREAD

**Issue by pascal-mueller** [Battleman/zoomdl#50] opened 2021-04-03 14:23 UTC
**Prerequisite**

- [x] I have updated to the latest version,
- [x] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [x] I have searched the opened and closed issues for a duplicate,

**Describe the bug**
I experience slow downloads with the newest version, about 90kbits. If I try the to download the same link with let's say 2021.02.15_beta version, I get 4 Mbps.

Also a minor typo: 91.5kit/s this is found in the progress bar, I guess it should be kbps or something like that.

**To Reproduce**
I don't have any public zoom video link but I guess just try it and confirm? But I tested it with several links.

**Versions (please complete the following information):**
 - OS: Arch
 - Python Version: 3.9.2

**Comment by Battleman** [comment] 2021-04-03 14:55
Duplicate of #49, closing to keep the discussion there.

**Closed by Battleman** 2021-04-03 14:55 UTC
Labels: bug
